/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:fea33b5c-196c-4a9d-8863-b4f1c20d8961",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_lXEq1GpIq",
    "aws_user_pools_web_client_id": "7n6n3dt42h58ppki8351hd6pgp",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "USER_NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
      "USER_NAME",
      "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
